services:
  db:
    image: percona:5.5
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      # ... other environment variables
  server:
    image: "admin/admin:latest"

    environment:
      DBUSER: admin
      DBPASSWORD: password
      # ... other environment variables
    depends_on:
      - db
    expose:
      - "3306"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "4000:4000"
